// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/soup.proto

package com.page.awesome.dto.proto;

import lombok.Data;

@Data
public final class SoupDto {
  private SoupDto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SoupOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tutorial.Soup)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string soupId = 1;</code>
     */
    boolean hasSoupId();
    /**
     * <code>optional string soupId = 1;</code>
     */
    java.lang.String getSoupId();
    /**
     * <code>optional string soupId = 1;</code>
     */
    com.google.protobuf.ByteString
        getSoupIdBytes();

    /**
     * <code>optional string chickenSoup = 2;</code>
     */
    boolean hasChickenSoup();
    /**
     * <code>optional string chickenSoup = 2;</code>
     */
    java.lang.String getChickenSoup();
    /**
     * <code>optional string chickenSoup = 2;</code>
     */
    com.google.protobuf.ByteString
        getChickenSoupBytes();

    /**
     * <code>optional int32 soupUp = 3;</code>
     */
    boolean hasSoupUp();
    /**
     * <code>optional int32 soupUp = 3;</code>
     */
    int getSoupUp();

    /**
     * <code>optional int32 soupDown = 4;</code>
     */
    boolean hasSoupDown();
    /**
     * <code>optional int32 soupDown = 4;</code>
     */
    int getSoupDown();

    /**
     * <code>optional float point = 5;</code>
     */
    boolean hasPoint();
    /**
     * <code>optional float point = 5;</code>
     */
    float getPoint();
  }
  /**
   * Protobuf type {@code tutorial.Soup}
   */
  public  static final class Soup extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tutorial.Soup)
      SoupOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Soup.newBuilder() to construct.
    private Soup(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Soup() {
      soupId_ = "";
      chickenSoup_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Soup(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              soupId_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              chickenSoup_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              soupUp_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              soupDown_ = input.readInt32();
              break;
            }
            case 45: {
              bitField0_ |= 0x00000010;
              point_ = input.readFloat();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SoupDto.internal_static_tutorial_Soup_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SoupDto.internal_static_tutorial_Soup_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SoupDto.Soup.class, SoupDto.Soup.Builder.class);
    }

    private int bitField0_;
    public static final int SOUPID_FIELD_NUMBER = 1;
    private volatile java.lang.Object soupId_;
    /**
     * <code>optional string soupId = 1;</code>
     */
    public boolean hasSoupId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string soupId = 1;</code>
     */
    public java.lang.String getSoupId() {
      java.lang.Object ref = soupId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          soupId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string soupId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSoupIdBytes() {
      java.lang.Object ref = soupId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        soupId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CHICKENSOUP_FIELD_NUMBER = 2;
    private volatile java.lang.Object chickenSoup_;
    /**
     * <code>optional string chickenSoup = 2;</code>
     */
    public boolean hasChickenSoup() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string chickenSoup = 2;</code>
     */
    public java.lang.String getChickenSoup() {
      java.lang.Object ref = chickenSoup_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          chickenSoup_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string chickenSoup = 2;</code>
     */
    public com.google.protobuf.ByteString
        getChickenSoupBytes() {
      java.lang.Object ref = chickenSoup_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        chickenSoup_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SOUPUP_FIELD_NUMBER = 3;
    private int soupUp_;
    /**
     * <code>optional int32 soupUp = 3;</code>
     */
    public boolean hasSoupUp() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional int32 soupUp = 3;</code>
     */
    public int getSoupUp() {
      return soupUp_;
    }

    public static final int SOUPDOWN_FIELD_NUMBER = 4;
    private int soupDown_;
    /**
     * <code>optional int32 soupDown = 4;</code>
     */
    public boolean hasSoupDown() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional int32 soupDown = 4;</code>
     */
    public int getSoupDown() {
      return soupDown_;
    }

    public static final int POINT_FIELD_NUMBER = 5;
    private float point_;
    /**
     * <code>optional float point = 5;</code>
     */
    public boolean hasPoint() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional float point = 5;</code>
     */
    public float getPoint() {
      return point_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, soupId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, chickenSoup_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeInt32(3, soupUp_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeInt32(4, soupDown_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeFloat(5, point_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, soupId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, chickenSoup_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, soupUp_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, soupDown_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(5, point_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof SoupDto.Soup)) {
        return super.equals(obj);
      }
      SoupDto.Soup other = (SoupDto.Soup) obj;

      if (hasSoupId() != other.hasSoupId()) return false;
      if (hasSoupId()) {
        if (!getSoupId()
            .equals(other.getSoupId())) return false;
      }
      if (hasChickenSoup() != other.hasChickenSoup()) return false;
      if (hasChickenSoup()) {
        if (!getChickenSoup()
            .equals(other.getChickenSoup())) return false;
      }
      if (hasSoupUp() != other.hasSoupUp()) return false;
      if (hasSoupUp()) {
        if (getSoupUp()
            != other.getSoupUp()) return false;
      }
      if (hasSoupDown() != other.hasSoupDown()) return false;
      if (hasSoupDown()) {
        if (getSoupDown()
            != other.getSoupDown()) return false;
      }
      if (hasPoint() != other.hasPoint()) return false;
      if (hasPoint()) {
        if (java.lang.Float.floatToIntBits(getPoint())
            != java.lang.Float.floatToIntBits(
                other.getPoint())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasSoupId()) {
        hash = (37 * hash) + SOUPID_FIELD_NUMBER;
        hash = (53 * hash) + getSoupId().hashCode();
      }
      if (hasChickenSoup()) {
        hash = (37 * hash) + CHICKENSOUP_FIELD_NUMBER;
        hash = (53 * hash) + getChickenSoup().hashCode();
      }
      if (hasSoupUp()) {
        hash = (37 * hash) + SOUPUP_FIELD_NUMBER;
        hash = (53 * hash) + getSoupUp();
      }
      if (hasSoupDown()) {
        hash = (37 * hash) + SOUPDOWN_FIELD_NUMBER;
        hash = (53 * hash) + getSoupDown();
      }
      if (hasPoint()) {
        hash = (37 * hash) + POINT_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getPoint());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static SoupDto.Soup parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SoupDto.Soup parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SoupDto.Soup parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SoupDto.Soup parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SoupDto.Soup parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SoupDto.Soup parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SoupDto.Soup parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SoupDto.Soup parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static SoupDto.Soup parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static SoupDto.Soup parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static SoupDto.Soup parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SoupDto.Soup parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(SoupDto.Soup prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tutorial.Soup}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tutorial.Soup)
        SoupDto.SoupOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SoupDto.internal_static_tutorial_Soup_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SoupDto.internal_static_tutorial_Soup_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                SoupDto.Soup.class, SoupDto.Soup.Builder.class);
      }

      // Construct using com.page.awesome.dto.proto.SoupDto.Soup.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        soupId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        chickenSoup_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        soupUp_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        soupDown_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        point_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SoupDto.internal_static_tutorial_Soup_descriptor;
      }

      @java.lang.Override
      public SoupDto.Soup getDefaultInstanceForType() {
        return SoupDto.Soup.getDefaultInstance();
      }

      @java.lang.Override
      public SoupDto.Soup build() {
        SoupDto.Soup result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public SoupDto.Soup buildPartial() {
        SoupDto.Soup result = new SoupDto.Soup(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.soupId_ = soupId_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.chickenSoup_ = chickenSoup_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.soupUp_ = soupUp_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.soupDown_ = soupDown_;
          to_bitField0_ |= 0x00000008;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.point_ = point_;
          to_bitField0_ |= 0x00000010;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof SoupDto.Soup) {
          return mergeFrom((SoupDto.Soup)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(SoupDto.Soup other) {
        if (other == SoupDto.Soup.getDefaultInstance()) return this;
        if (other.hasSoupId()) {
          bitField0_ |= 0x00000001;
          soupId_ = other.soupId_;
          onChanged();
        }
        if (other.hasChickenSoup()) {
          bitField0_ |= 0x00000002;
          chickenSoup_ = other.chickenSoup_;
          onChanged();
        }
        if (other.hasSoupUp()) {
          setSoupUp(other.getSoupUp());
        }
        if (other.hasSoupDown()) {
          setSoupDown(other.getSoupDown());
        }
        if (other.hasPoint()) {
          setPoint(other.getPoint());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        SoupDto.Soup parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (SoupDto.Soup) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object soupId_ = "";
      /**
       * <code>optional string soupId = 1;</code>
       */
      public boolean hasSoupId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional string soupId = 1;</code>
       */
      public java.lang.String getSoupId() {
        java.lang.Object ref = soupId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            soupId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string soupId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSoupIdBytes() {
        java.lang.Object ref = soupId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          soupId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string soupId = 1;</code>
       */
      public Builder setSoupId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        soupId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string soupId = 1;</code>
       */
      public Builder clearSoupId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        soupId_ = getDefaultInstance().getSoupId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string soupId = 1;</code>
       */
      public Builder setSoupIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        soupId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object chickenSoup_ = "";
      /**
       * <code>optional string chickenSoup = 2;</code>
       */
      public boolean hasChickenSoup() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional string chickenSoup = 2;</code>
       */
      public java.lang.String getChickenSoup() {
        java.lang.Object ref = chickenSoup_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            chickenSoup_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string chickenSoup = 2;</code>
       */
      public com.google.protobuf.ByteString
          getChickenSoupBytes() {
        java.lang.Object ref = chickenSoup_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          chickenSoup_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string chickenSoup = 2;</code>
       */
      public Builder setChickenSoup(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        chickenSoup_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string chickenSoup = 2;</code>
       */
      public Builder clearChickenSoup() {
        bitField0_ = (bitField0_ & ~0x00000002);
        chickenSoup_ = getDefaultInstance().getChickenSoup();
        onChanged();
        return this;
      }
      /**
       * <code>optional string chickenSoup = 2;</code>
       */
      public Builder setChickenSoupBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        chickenSoup_ = value;
        onChanged();
        return this;
      }

      private int soupUp_ ;
      /**
       * <code>optional int32 soupUp = 3;</code>
       */
      public boolean hasSoupUp() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional int32 soupUp = 3;</code>
       */
      public int getSoupUp() {
        return soupUp_;
      }
      /**
       * <code>optional int32 soupUp = 3;</code>
       */
      public Builder setSoupUp(int value) {
        bitField0_ |= 0x00000004;
        soupUp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 soupUp = 3;</code>
       */
      public Builder clearSoupUp() {
        bitField0_ = (bitField0_ & ~0x00000004);
        soupUp_ = 0;
        onChanged();
        return this;
      }

      private int soupDown_ ;
      /**
       * <code>optional int32 soupDown = 4;</code>
       */
      public boolean hasSoupDown() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional int32 soupDown = 4;</code>
       */
      public int getSoupDown() {
        return soupDown_;
      }
      /**
       * <code>optional int32 soupDown = 4;</code>
       */
      public Builder setSoupDown(int value) {
        bitField0_ |= 0x00000008;
        soupDown_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 soupDown = 4;</code>
       */
      public Builder clearSoupDown() {
        bitField0_ = (bitField0_ & ~0x00000008);
        soupDown_ = 0;
        onChanged();
        return this;
      }

      private float point_ ;
      /**
       * <code>optional float point = 5;</code>
       */
      public boolean hasPoint() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>optional float point = 5;</code>
       */
      public float getPoint() {
        return point_;
      }
      /**
       * <code>optional float point = 5;</code>
       */
      public Builder setPoint(float value) {
        bitField0_ |= 0x00000010;
        point_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float point = 5;</code>
       */
      public Builder clearPoint() {
        bitField0_ = (bitField0_ & ~0x00000010);
        point_ = 0F;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:tutorial.Soup)
    }

    // @@protoc_insertion_point(class_scope:tutorial.Soup)
    private static final SoupDto.Soup DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new SoupDto.Soup();
    }

    public static SoupDto.Soup getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Soup>
        PARSER = new com.google.protobuf.AbstractParser<Soup>() {
      @java.lang.Override
      public Soup parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Soup(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Soup> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Soup> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public SoupDto.Soup getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_Soup_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_Soup_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020proto/soup.proto\022\010tutorial\"\\\n\004Soup\022\016\n\006" +
      "soupId\030\001 \001(\t\022\023\n\013chickenSoup\030\002 \001(\t\022\016\n\006sou" +
      "pUp\030\003 \001(\005\022\020\n\010soupDown\030\004 \001(\005\022\r\n\005point\030\005 \001" +
      "(\002B\037\n\024com.page.awesome.dtoB\007SoupDto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_tutorial_Soup_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tutorial_Soup_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_Soup_descriptor,
        new java.lang.String[] { "SoupId", "ChickenSoup", "SoupUp", "SoupDown", "Point", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
